### ISSUE TITLE
Error while executing SQL query on database 'qnap': 1st ORDER BY term out of range - should be between 1 and 1

### ISSUE THREAD

**Issue by audiomuze** [pawelsalawa/sqlitestudio#4824]
### Details
I have a table containing a field ```sqlmodded``` which is updated by the trigger set out below.  The table is populated using external source data and in all instances ```sqlmodded``` will be ```NULL``` on populating the table.  The trigger is as follows:
```
CREATE TRIGGER IF NOT EXISTS sqlmods
                       AFTER UPDATE
                          ON alib
                    FOR EACH ROW
                        WHEN old.sqlmodded IS NULL
BEGIN
    UPDATE alib
       SET sqlmodded = iif(sqlmodded IS NULL, '1', (CAST (sqlmodded AS INTEGER) + 1) ) 
     WHERE rowid = NEW.rowid;
END;
```
If I open the table in SQLiteStudio and run the following it returns the number of records that do not have NULL in ```sqlmodded```:
```
SELECT count(sqlmodded) 
  FROM alib;
```
All of the above works as intended, until I run an update query.  The trigger continues to behave correctly, incrementing ```sqlmodded``` as appropriate.  However, after running an update query if you rerun 
```
SELECT count(sqlmodded) 
  FROM alib;
```
then SQLiteStudio throws the error: ```Error while executing SQL query on database 'qnap': 1st ORDER BY term out of range - should be between 1 and 1```.

Doing exactly the same with DB Browser for SQLite Version 3.12.2 **_does not throw an error_**.

### Steps to reproduce
Define and use trigger as outlined above.  Run ```SELECT count(sqlmodded)```

### Operating system
Arch Linux 6.4.2-arch1-1, KDE Plasma.

### SQLiteStudio version
3.4.4

**Comment by pawelsalawa** [comment]
This is most likely a duplicate of #4819

Problem appears if you double-click on results column header to sort it and then you run another query. It will be fixed.

For now, if you encounter this error, you can close the editor window and reopen it (use right-click on bottom bar to reopen recently closed window to restore editor's contents too).

**Comment by audiomuze** [comment]
@pawelsalawa Thanks.  And thanks for the many improvements and bugfixes in 3.4.4.

**Comment by tuffnatty** [comment]
Probably fixed with #5032.

**Comment by pawelsalawa** [comment]
I'll keep it open, until I have time to verify it really is the same issue.

**Comment by pawelsalawa** [comment]
Coming back to this, I find it complex to try reproducing it by myself to confirm it's fixed. After all I will assume it was fixed with #5032, as you suggested @tuffnatty and if cany case, @audiomuze can always come back here and say it's still a problem.

**Comment by audiomuze** [comment]
I've not encountered it in 3.4.4, but most of my work has been in Python/SQLite of late.   I'm in the process now of developing additional queries - which always start life in SQLiteStudio, so will report if the issue resurfaces.  Thx
